server:
    port: 8086
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: "localhost"
    port: 5672
  datasource:
    url: "jdbc:mysql://82.73.212.90:3307/dpm"
    username: "2nowabout"
    password: "SecurePassword1!"